name: Testing
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test (C++)
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -y -q install cmake gcc g++ libopenblas-dev libeigen3-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install ARPACK-NG
        run: |
          git clone https://github.com/opencollab/arpack-ng.git
          cd arpack-ng
          cmake -Bbuild .
          cmake --build ./build
          sudo cmake --build ./build --target install

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test
        run: |
          cmake -BBuildTests -DBUILD_TESTS=ON .
          cmake --build ./BuildTests --target runner
          cmake --build ./BuildTests --target test
        env:
          LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"
